//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Transversal.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Transversal.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado el registro exitosamente.
        /// </summary>
        public static string CreacionExitosa {
            get {
                return ResourceManager.GetString("CreacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha realizado la actualziación exitosamente.
        /// </summary>
        public static string EdicionExitosa {
            get {
                return ResourceManager.GetString("EdicionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado el registro exitosamente.
        /// </summary>
        public static string EliminacionExitosa {
            get {
                return ResourceManager.GetString("EliminacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el registro a eliminar.
        /// </summary>
        public static string EliminacionFallida {
            get {
                return ResourceManager.GetString("EliminacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ocurrido un error creando el registro.
        /// </summary>
        public static string ErrorEnCreacion {
            get {
                return ResourceManager.GetString("ErrorEnCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ocurrido un error actualizando la información.
        /// </summary>
        public static string ErrorEnEdición {
            get {
                return ResourceManager.GetString("ErrorEnEdición", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ocurrido un error eliminando el registro.
        /// </summary>
        public static string ErrorEnEliminacion {
            get {
                return ResourceManager.GetString("ErrorEnEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta exitosa.
        /// </summary>
        public static string RespuestaConData {
            get {
                return ResourceManager.GetString("RespuestaConData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A ocurrido un error procesando la operación.
        /// </summary>
        public static string RespuestaFallida {
            get {
                return ResourceManager.GetString("RespuestaFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrados registros con los parametros de busqueda.
        /// </summary>
        public static string RespuestaVacia {
            get {
                return ResourceManager.GetString("RespuestaVacia", resourceCulture);
            }
        }
    }
}
